apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend-deployment
  labels:
    app: beckend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: beckend
  template:
    metadata:
      labels:
        app: beckend
    spec:
      containers:
        - name: beckendcont
          image:  frenzy669/docker-backend-service:latest
          ports:
            - containerPort: 5002
---            
apiVersion: v1
kind: Service
metadata:
  name: beckend-service
spec:
  selector:
    app: beckend
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
    