version: '3.8'
services:
  web:
    build: ./fe
    depends_on:
     - backend-service
    ports:
      - "5002:5002"
    networks:
      - mynet



  backend-service:
    build: ./be
    depends_on:
      # - mysqldb
      mysqldb:
        condition: service_healthy
    # environment:
    #   MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - "5006:5001"
    networks:
      - mynet


  mysqldb:
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: "crypto_db"
      networks:
        - mynet
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 10s
        retries: 5
        start_period: 30s


networks:
  mynet:
    driver: bridge
