apiVersion: apps/v1
kind: Deployment
metadata: 
  name: fronted-deployment
  labels:
    app: front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: frontcont
          image:  frenzy669/docker-web:latest
          ports:
            - containerPort: 5002
          env:
            - name: BACKEND_URL
              value: "http://backend-service:5001"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: front
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002
    